### PR TITLE
Count routing keys

### PR DESCRIPTION
**Pull request by shaqq**
@danielmackey 

When you've got a lot of messages, it helps to get an idea of how many per routing_key

### CODE REVIEW

**Comment by shaqq** [comment]
also,

**Comment by danielmackey** [comment]
I wonder if we could make the counter hash its own object that knows how to increment a given key.

**Comment by shaqq** [comment]
@danielmackey I abstracted it into a pretty naive one. Does that work, or do you want it a little more fleshed out?

**Comment by danielmackey** [comment]
Looks good! Thanks for contributing!

**Pull request merged**
